options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: E2_HIGHCPU_8
substitutions:
  _REGION: us-east1
  _SERVICE_NAME: estatewise-backend
  _ARTIFACT_REPO: us-east1-docker.pkg.dev/$PROJECT_ID/estatewise
  _SERVICE_ACCOUNT: estatewise-run@$PROJECT_ID.iam.gserviceaccount.com
steps:
  - id: 'Install backend dependencies'
    name: 'gcr.io/cloud-builders/npm'
    dir: backend
    args: ['ci']

  - id: 'Run backend tests'
    name: 'gcr.io/cloud-builders/npm'
    dir: backend
    args: ['test', '--', '--watch=false']

  - id: 'Build backend container'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_ARTIFACT_REPO}/backend:$COMMIT_SHA',
        '-f',
        'backend/Dockerfile',
        '.',
      ]

  - id: 'Push backend container'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REPO}/backend:$COMMIT_SHA']

  - id: 'Tag latest'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker tag ${_ARTIFACT_REPO}/backend:$COMMIT_SHA ${_ARTIFACT_REPO}/backend:latest
        docker push ${_ARTIFACT_REPO}/backend:latest

  - id: 'Deploy Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_ARTIFACT_REPO}/backend:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=3001
      - --execution-environment=gen2
      - --min-instances=1
      - --max-instances=20
      - --cpu=1
      - --memory=1Gi
      - --vpc-connector=estatewise-connector
      - --vpc-egress=all-traffic
      - --set-secrets=MONGO_URI=MONGO_URI:latest,PINECONE_API_KEY=PINECONE_API_KEY:latest,GOOGLE_AI_API_KEY=GOOGLE_AI_API_KEY:latest,JWT_SECRET=JWT_SECRET:latest
      - --set-env-vars=NODE_ENV=production,PINECONE_INDEX=estatewise-index
      - --service-account=${_SERVICE_ACCOUNT}

images:
  - '${_ARTIFACT_REPO}/backend:$COMMIT_SHA'
